### ISSUE TITLE
nvidia-ml-py package installation

### ISSUE THREAD

**Issue by Neronjust2017** [XuehaiPan/nvitop#1]
hi，老哥，我安装好之后，输入nvitop会出现这个错误：
```
ERROR: Some FunctionNotFound errors occurred while calling:
    nvmlQuery('nvmlDeviceGetGraphicsRunningProcesses', *args, **kwargs)
    nvmlQuery('nvmlDeviceGetComputeRunningProcesses', *args, **kwargs)
Please verify whether the nvidia-ml-py package is compatible with your NVIDIA driver version.
You can check the release history of nvidia-ml-py at https://pypi.org/project/nvidia-ml-py/#history,
and install the compatible version manually.
```
但是，我安装其他版本的nvidia-ml-py，会出现：
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nvitop 0.3.5.4 requires nvidia-ml-py==11.450.51, but you have nvidia-ml-py 7.352.0 which is incompatible.
```
看起来nvitop需要nvidia-ml-py==11.450.51，但是我的显卡驱动又和nvidia-ml-py版本不兼容，有解决办法吗？

**Comment by XuehaiPan** [comment]
感谢反馈！能给一下你的操作系统版本和驱动版本吗？第二个 pip 安装其他版本的 nvidia-ml-py 的 warning 直接忽略就好了。

由于 nvidia-ml-py、py3nvml、nvidia-ml-py3 这三个包都会安装 pynvml.py 这个文件，能确认一下你是否安装了其他两个包吗？

```bash
pip3 freeze
```

后面两个包可能是安装了其他的库作为依赖安装的（比如 glances / gpustat），然后把 pynvml.py 给修改了。

**Comment by Neronjust2017** [comment]
- OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
- GPU model and memory: Tesla P100-PCIE 16GB
- GPU diver version: 440.33.01

其他两个包都没有安装，但我发现安装了pynvml==11，我uninstall pynvml 之后再重新安装nvitop就没问题了。

**Comment by XuehaiPan** [comment]
> 我uninstall pynvml 之后再重新安装nvitop就没问题了。

好的！如果和其他库冲突，可以用 virtualenv 之类的做个隔离。
