### ISSUE TITLE
[Feature Request] Add shortcut that shows parent process's name for selected process

### ISSUE THREAD

**Issue by ubless607** [XuehaiPan/nvitop#102]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Motivation

![image](https://github.com/XuehaiPan/nvitop/assets/5417257/2698b79e-c5c2-4487-8d37-6b97aa5a12b6)

Training a deep learning model with [pytorch ddp](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html) is useful because it can utilize multiple gpus simultaneously.

The "COMMAND" description is not enough to get the information user need.

[setproctitle](https://github.com/dvarrazzo/py-setproctitle) allows user to change the name of a process.
If there was a shortcut to show the name of the parent process for the selected process, the user could distinguish the origin of the process or the purpose of the process.

Currently, user can use the tree-view mode to see the name of the parent process.
I would like to use a toggle shortcut working on the main screen. It would be useful for users working in the field of deep learning.

**Comment by XuehaiPan** [comment]
Hi @ubless607, you can press the `t` key to switch to the treeview screen. That will show the GPU processes and their ancestors.
