### ISSUE TITLE
[BUG][exporter] Process metrics still exist when the process is gone

### ISSUE THREAD

**Issue by caotangdaiduong** [XuehaiPan/nvitop#106]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### What version of nvitop are you using?

1.3.1

### Operating system and version

Ubuntu 20.04.4 LTS

### NVIDIA driver version

510.47.03

### NVIDIA-SMI

```text
Wed Nov 22 16:23:39 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:07:00.0 Off |                    0 |
| N/A   36C    P0    64W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  Off  | 00000000:0F:00.0 Off |                    0 |
| N/A   49C    P0   309W / 400W |  47128MiB / 81920MiB |     41%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM...  Off  | 00000000:47:00.0 Off |                    0 |
| N/A   46C    P0   113W / 400W |  48588MiB / 81920MiB |     75%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM...  Off  | 00000000:4E:00.0 Off |                    0 |
| N/A   51C    P0   237W / 400W |  36364MiB / 81920MiB |     76%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A100-SXM...  Off  | 00000000:87:00.0 Off |                    0 |
| N/A   52C    P0   216W / 400W |  42424MiB / 81920MiB |     50%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A100-SXM...  Off  | 00000000:90:00.0 Off |                    0 |
| N/A   44C    P0    69W / 400W |      0MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A100-SXM...  Off  | 00000000:B7:00.0 Off |                    0 |
| N/A   47C    P0    71W / 400W |  60528MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A100-SXM...  Off  | 00000000:BD:00.0 Off |                    0 |
| N/A   49C    P0    76W / 400W |  72888MiB / 81920MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
 
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    1   N/A  N/A   3092375      C   ...vs/mask2former/bin/python    47125MiB |
|    2   N/A  N/A   3092376      C   ...vs/mask2former/bin/python    48585MiB |
|    3   N/A  N/A   3092377      C   ...vs/mask2former/bin/python    36361MiB |
|    4   N/A  N/A   3092374      C   ...vs/mask2former/bin/python    42421MiB |
|    6   N/A  N/A   3623277      C   ...onda3/envs/ivy/bin/python    60399MiB |
|    7   N/A  N/A   3623278      C   ...onda3/envs/ivy/bin/python    72759MiB |
+-----------------------------------------------------------------------------+
```

### Python environment

3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0] linux
nvidia-ml-py==12.535.133
nvitop==1.3.1
nvitop-exporter==1.3.1

### nvitop-exporter cache value
Metric values are retained and not refreshed

Before restart nvitop-exporter
![image](https://github.com/XuehaiPan/nvitop/assets/28684084/d6b0e382-cae6-4e83-9e23-9ede62cb7084)

After restart nvitop-exporter
![image](https://github.com/XuehaiPan/nvitop/assets/28684084/b5a6a622-6d95-4bf4-bfe0-a131948baade)

### Steps to Reproduce

The Python snippets (if any):

```python

```

Command lines:

```bash

```

**Comment by XuehaiPan** [comment]
> Metric values are retained and not refreshed

Hi @caotangdaiduong, do you set up a `prometheus` service to retrieve the latest metrics automatically?

**Comment by caotangdaiduong** [comment]
Sure, below is my configuration:

```
- job_name: 'nvitop-exporter'
  scrape_interval: 60s
  static_configs:
  - targets:
    - 10.17.72.191:9301
    - 10.17.72.192:9301
    - 10.17.72.193:9301
    - 10.17.72.194:9301
    - 10.17.72.195:9301
    - 10.17.72.196:9301
```

And here is systemd service:

```
cat << EOF > /etc/systemd/system/nvitop-exporter.service
[Unit]
Description=nvitop-exporter
ConditionPathExists=/usr/bin/nvitop-exporter
After=network.target

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/usr/bin/
ExecStart=/usr/bin/nvitop-exporter --bind-address 0.0.0.0 --port 9301 --interval 30
LimitNOFILE=102400
LimitNOFILESoft=102400
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

systemctl restart nvitop-exporter.service
systemctl enable nvitop-exporter.service
systemctl status nvitop-exporter.service
```

I know by default nvitop default interval is 1s but I have added the interval option with different values like 15s, 30s but the result is still the same.

This is similar to pushgateway, it only updates the value with the last key name and if there is a new key, there will be new values. I think it's similar to the case with many different values (in my case, every time the PID, index is changed, it creates a new one, and the old PID, index is still there).

**Comment by XuehaiPan** [comment]
> I know by default nvitop default interval is 1s but I have added the interval option with different values like 15s, 30s but the result is still the same.

@caotangdaiduong I can see the metrics are updating on my side. I'm running `watch --differences`:

```bash
watch --differences 'curl -s http://127.0.0.1:8000/metrics'
```

> This is similar to pushgateway, it only updates the value with the last key name and if there is a new key, there will be new values. I think it's similar to the case with many different values (in my case, every time the PID, index is changed, it creates a new one, and the old PID, index is still there).

The metrics for GPU processes are actively updated on my side.

I can confirm if the GPU process is gone, the gauge keys still exist. Do you mean you want to remove these keys if the corresponding processes are gone?

**Comment by caotangdaiduong** [comment]
You can perform the test again with the following steps:
- Run 1 or several processes on GPU index 0 ==> Remember this PID
- Wait 5-10 minutes
- Then kill the old pid and run with a new process and new GPU index ==> Remember this PID
Then test the curl with any metric. You will see that both the old and new PIDs exist when calling curl to the exporter
---
watch --differences only shows the changes, but the old value will still exist, you should use grep and check the grep result against the real thing, as you did above.
---
I have 6 servers running A100 and all exporters on 6 servers have the same error
---
Also, if I move the binary to another folder, will it have any effect?
```
pip3 install --upgrade nvitop-exporter
DIR=$(which nvitop-exporter)
sudo mv $DIR /usr/bin/
which nvitop-exporter
```

**Comment by XuehaiPan** [comment]
> * You will see that both the old and new PIDs exist when calling curl to the exporter

@caotangdaiduong I can confirm this and opened a PR #107 to resolve this. You can try it via:

```python
python3 -m pip install "git+https://github.com/XuehaiPan/nvitop.git@exporter-remove-gone-process#egg=nvitop-exporter&subdirectory=nvitop-exporter"
```

**Comment by caotangdaiduong** [comment]
Hi @XuehaiPan 

Thanks for your efforts, I tested it and it works as expected
