### ISSUE TITLE
[Feature Request] Show real-time bandwidth under monitor mode

### ISSUE THREAD

**Issue by CarlGao4** [XuehaiPan/nvitop#117]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [ ] I have tried the latest version of nvitop in a new isolated virtual environment.

### Motivation

Just like nvtop, but nvitop is far better than nvtop (except monitoring RX and TX)
![image](https://github.com/XuehaiPan/nvitop/assets/57826826/beabd52d-fe13-4fa5-8bc5-643ac536fd00)

**Comment by XuehaiPan** [comment]
Hi, I think you would love the new Grafana dashboard approach. Checkout the README.
