### ISSUE TITLE
[Question]  How snapshot could be used

### ISSUE THREAD

**Issue by Xiang-cd** [XuehaiPan/nvitop#119]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [ ] I have tried the latest version of nvitop in a new isolated virtual environment.

### Questions

thank you for your great work! I've seen the as_snapshot function, but I was wondering how the snapshot could be used?
is the snapshot resumable? because I didn't see the resume interface.

**Comment by XuehaiPan** [comment]
@Xiang-cd Thanks for raising this.

The `Device` / `GpuProcess` instance is live object to get the latest metrics via method calls. E.g.:

```python
device = Device(0)

device.gpu_utilization()  # -> 96
time.sleep(1)
device.gpu_utilization()  # -> 80  # the latest value from a new NVML API call
```

Once it is converted to snapshot, the metrics are forzen. The metrcis values are obtained at the time you call `as_snapshot()`.

```python
device = Device(0)

snapshot = device.as_snapshot()
snapshot.gpu_utilization  # -> 94
time.sleep(1)
snapshot.gpu_utilization  # -> 94 (always the freezed value)
```

You can access the device object via:

```python
snapshot = device.as_snapshot()

snapshot.real  # -> Device(...)

# Get a new snapshot
snapshot = snapshot.real.as_snapshot()
# or
snapshot = device.as_snapshot()
```

**Comment by Xiang-cd** [comment]
thank you, so the snapshot is not a context containing all memory content and register status that could move all context of one device to another device?
