### ISSUE TITLE
Installation: which step to follow?

### ISSUE THREAD

**Issue by moreje** [XuehaiPan/nvitop#120]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Questions

I'm a bit confuse with the install steps described here?
are they alternative steps? or do we have to follow all of them?
Also, I try to install nvitop on my OMV server, but I get the following:
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.
```
Any suggestions?
thank for your help

**Comment by XuehaiPan** [comment]
Hi @moreje, sorry for the late reply. You could install [`pipx`](https://pipx.pypa.io/stable) and run `nvitop` via:

```bash
pipx run nvitop
```
