### ISSUE TITLE
[Feature Request] can you support word wrap for COMMAND information

### ISSUE THREAD

**Issue by milk-bottle-liyu** [XuehaiPan/nvitop#124]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [ ] I have tried the latest version of nvitop in a new isolated virtual environment.

### Motivation

Most of my programs takes a lot of input parameters, so the commands will be pretty long. Currently I have to use arrow key to check the parameters and it is inconvenient and easy to make a mistake. If you can support word wrap for COMMAND information, it will help me a lot as I can compare the commands within one look.

### Additional context

![image](https://github.com/XuehaiPan/nvitop/assets/17823646/afc4db71-cbc6-4543-bffe-41f081cd3d60)

Thanks for reading this issues and I should say `nvitop` is a very impressive tool for me 😊.

**Comment by XuehaiPan** [comment]
Hi @milk-bottle-liyu, maybe you can press the `t` key to view `COMMAND`s in the treeview screen. It scrolls faster horizontally and has more width to show more information. FYI, you can hold the `CTRL` key while scrolling the command list with our mouse.

I'm sorry that there are no similar features in `top`-like monitoring tools. And it may not be implemented.
