### ISSUE TITLE
Windows download link please.. 

### ISSUE THREAD

**Issue by Drhicom** [XuehaiPan/nvitop#125]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Questions

Windows download link please..

**Comment by XuehaiPan** [comment]
Hi @Drhicom, you could install a Python distribution and install `nvitop` via `pip`.

```bash
choco install python --yes
python3 -m pip install --upgrade pip setuptools
python3 -m pip install nvitop
python3 -m nvitop
```
