### ISSUE TITLE
[Feature Request] Nvitop-Exporter: Processes name & args (command)

### ISSUE THREAD

**Issue by StefanSander3** [XuehaiPan/nvitop#133]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Questions

Hey there,

as mentioned in #122 I would upload my dashboard I'm working on right now, if Grafana is still offering this technique.

I don't see a metric offering **process name and args** (command) and I would profit a lot from those, it's kind of critical to make the dashboard work for my users.

To make a dashboard/nvitop-exporter even more successful, having that in the exporter by default would be a big benefit in my perspective.

**Comment by XuehaiPan** [comment]
A new release is made to resolve this.
