### ISSUE TITLE
[Question] Missing font 

### ISSUE THREAD

**Issue by legraphista** [XuehaiPan/nvitop#135]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Questions

Hello :wave: 

I'm running `nvitop` on an Ubuntu 24.04 server with console screen output. Which font should be installed to have the braille show up properly for the charts?
![original_8df205ca-09dc-49d9-a9d5-e931f51d9cb4_PXL_20241004_104550279](https://github.com/user-attachments/assets/b8fad267-99ee-4b6f-b16a-af2b6556346e)

**Comment by XuehaiPan** [comment]
Hi @legraphista, I think the console cannot show these Unicode characters properly. You should login with a Desktop session and use the Terminal emulator. In the console, you can use:

```bash
nvitop -U
```

to disable Unicode output.
