### ISSUE TITLE
[Question] How on earth does the sorting work?

### ISSUE THREAD

**Issue by smbell1979** [XuehaiPan/nvitop#137]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Questions

I might be an idiot, but I cannot for the life of me, figure out how to sort by CPU usage, or GPU usage for instance...

What does oc oC or og oG mean?   Is this a combo of o and c, because I can't get it to work.

**Comment by XuehaiPan** [comment]
Hi @smbell1979, the combination key means sequentially pressing the keys one-by-one. If you are familiar with vim/vi, I think you can understand that easily.

```text
oc:
<press> o
<release>
<press> c
<release>

oC:
<press> o
<release>
<press and hold> shift
<press> c
<release>
```
