### ISSUE TITLE
[BUG] Release changelog URLs are incorrect

### ISSUE THREAD

**Issue by keith** [XuehaiPan/nvitop#140]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [ ] I have tried the latest version of nvitop in a new isolated virtual environment.

### What version of nvitop are you using?

n/a

### Operating system and version

n/a

### NVIDIA driver version

n/a

### Python environment

n/a

### Problem description

On the release page: https://github.com/XuehaiPan/nvitop/releases

the "full changelog" urls 404, they are missing the repo name:

current: https://github.com/XuehaiPan/compare/v1.3.0...v1.3.1
correct: https://github.com/XuehaiPan/nvitop/compare/v1.3.1...v1.3.2

### Steps to Reproduce

n/a

**Comment by XuehaiPan** [comment]
Thanks for the report. I'll update the URLs in the next release.
