### ISSUE TITLE
[Question] Create new release for vllm compatibility

### ISSUE THREAD

**Issue by keith** [XuehaiPan/nvitop#141]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [ ] I have tried the latest version of nvitop in a new isolated virtual environment.

### Questions

Because of conflicting dependency issues with the latest nvitop release (1.3.1), you cannot install the latest vllm in the same virtualenv with nvitop:

```
$ pip3 install vllm==0.6.4 nvitop
ERROR: Cannot install nvitop==0.10.0, nvitop==0.10.1, nvitop==0.10.2, nvitop==0.11.0, nvitop==0.9.0, nvitop==1.0.0, nvitop==1.1.1, nvitop==1.1.2, nvitop==1.2.0, nvitop==1.3.0, nvitop==1.3.1, nvitop==1.3.2 and vllm==0.6.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    vllm 0.6.4 depends on nvidia-ml-py>=12.560.30
    nvitop 1.3.2 depends on nvidia-ml-py<12.536.0a0 and >=11.450.51
    vllm 0.6.4 depends on nvidia-ml-py>=12.560.30
    nvitop 1.3.1 depends on nvidia-ml-py<12.536.0a0 and >=11.450.51
    vllm 0.6.4 depends on nvidia-ml-py>=12.560.30
    nvitop 1.3.0 depends on nvidia-ml-py<12.536.0a0 and >=11.450.51
    vllm 0.6.4 depends on nvidia-ml-py>=12.560.30
...
```

This is fixed @ HEAD so it would be great if there was a new pypi release with this version bump fix!

**Comment by XuehaiPan** [comment]
Thanks for raising this. I will create a version bump for this.

> you cannot install the latest vllm in the same virtualenv with nvitop

Also, I'd suggest to install `nvitop` using `pipx` or `uvx` instead of install it in your virtual environment:

```bsah
pipx run nvitop
# or
uvx nvitop
```

You can add alias in your shell rc:

```bash
alias nvitop='pipx run nvitop'
# or
alias nvitop='uvx nvitop'
```

**Comment by XuehaiPan** [comment]
A new release is made.

**Comment by keith** [comment]
thanks!
