### ISSUE TITLE
[Bug] display issue when running inside tmux

### ISSUE THREAD

**Issue by Cveinnt** [XuehaiPan/nvitop#16]
#### Runtime Environment

- Operating system and version: Ubuntu 16.04 LTS 
- Terminal emulator and version: iTerm2 3.4.15
- Python version: 3.9.7
- NVML version (driver version): 470.57
- `nvitop` version: main@latest
- Locale: en_US.UTF-8

#### Current Behavior
When running `nvitop` inside tmux, the rendered display will become messed up, as shown in the screenshots. This behavior is not present when not using tmux.

#### Steps to Reproduce

1. open a tmux session
2. run nvitop

#### Images / Videos  
![scrnsht](https://user-images.githubusercontent.com/30604389/167857603-4ebc430f-e249-461e-a427-5ee5db45ee25.png)

**Comment by XuehaiPan** [comment]
Hi @Cveinnt, what's your `tmux` version?

```bash
tmux -V
```

Is your `tmux` compiled with `ncurses` correctly?

I cannot reproduce this on my Ubuntu 16.04 LTS machine with `tmux` 2.1 and ncurses 5.

**Comment by Cveinnt** [comment]
Hi @XuehaiPan ,
`tmux -V` yields `tmux 2.1` for me. 
I installed the package with `apt`, and have no previous display issue with tmux prior.
The bug only seems to appear when `nvitop` is in resource monitor mode (in tmux), as `nvitop -1` etc. still produces normal display.

**Comment by XuehaiPan** [comment]
Can you try:

```python
strace tmux -c 'python3 -c "import curses; win = curses.init_scr(); curses.endwin()"' 2>&1 | grep -E '.*curses.*.so'
```

------

> The bug only seems to appear when `nvitop` is in resource monitor mode (in tmux), as `nvitop -1` etc. still produces normal display.

`nvitop -1` will not initialize ncurses window. It just print results to the terminal.

**Comment by Cveinnt** [comment]
Here's the output 

```bash
stat(".../miniconda3/lib/python3.9/curses/__init__.cpython-39-x86_64-linux-gnu.so", 0x7ffe7a0fc580) = -1 ENOENT (No such file or directory)
stat(".../miniconda3/lib/python3.9/curses/__init__.abi3.so", 0x7ffe7a0fc580) = -1 ENOENT (No such file or directory)
stat(".../miniconda3/lib/python3.9/curses/__init__.so", 0x7ffe7a0fc580) = -1 ENOENT (No such file or directory)
stat(".../miniconda3/lib/python3.9/lib-dynload/_curses.cpython-39-x86_64-linux-gnu.so", {st_mode=S_IFREG|0775, st_size=471008, ...}) = 0
open(".../miniconda3/lib/python3.9/lib-dynload/_curses.cpython-39-x86_64-linux-gnu.so", O_RDONLY|O_CLOEXEC) = 3
open(".../miniconda3/lib/python3.9/lib-dynload/../../tls/x86_64/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open(".../miniconda3/lib/python3.9/lib-dynload/../../tls/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open(".../miniconda3/lib/python3.9/lib-dynload/../../x86_64/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open(".../miniconda3/lib/python3.9/lib-dynload/../../libncursesw.so.6", O_RDONLY|O_CLOEXEC) = 3
```
It looks like python is looking for `libncursesw6`, when I only have 5.

**Comment by XuehaiPan** [comment]
@Cveinnt You can uninstall `nvitop` in your conda environment. Then install it with system Python:

```bash
sudo apt install python3-dev python3-pip
/usr/bin/python3 -m pip install --user nvitop
```

```bash
～/.local/bin/nvitop
```

**Comment by Cveinnt** [comment]
Thanks - this worked for me. Closing the issue now.
