### ISSUE TITLE
make snapshot interval configurable in monitor mode

### ISSUE THREAD

**Issue by uwydoc** [XuehaiPan/nvitop#17]
just a small feature request, it would be better to make the snapshot interval configurable in monitor mode. a quick grep shows that there are multiple snapshot intervals, some are defined as class members, others are plain constant value in `time.sleep(xxx)`

**Comment by XuehaiPan** [comment]
> just a small feature request, it would be better to make the snapshot interval configurable in monitor mode.

Hi @uwydoc, thanks for the post. I arbitrarily hardcoded the snapshot intervals in `nvitop` for performance issues. Taking snapshots is I/O intensive, especially when there are many processes on GPUs. I think we should not do this so frequently. `nvitop` takes snapshots for GPU device status every 1 second, and every 2 seconds for GPU processes.

Opinions are welcome. Can you give some use cases?

------

> a quick grep shows that there are multiple snapshot intervals, some are defined as class members, others are plain constant value in time.sleep(xxx)

The class members (`0.7` here)

https://github.com/XuehaiPan/nvitop/blob/f73b7d84c59c03f6cd8402b01018ae4a6990a653/nvitop/gui/screens/main/device.py#L16-L19

are not actual snapshot intervals. They only account for syncing results between threads.

The effective intervals are defined by `ttl_cache`:

https://github.com/XuehaiPan/nvitop/blob/f73b7d84c59c03f6cd8402b01018ae4a6990a653/nvitop/gui/screens/main/device.py#L98-L100

https://github.com/XuehaiPan/nvitop/blob/f73b7d84c59c03f6cd8402b01018ae4a6990a653/nvitop/gui/screens/main/process.py#L169-L172

**Comment by uwydoc** [comment]
well, i was planning to make the interval longer, say 3 seconds for process snapshot and gui refresh, to make its cpu load lower (0.2~0.3 currently). the default settings are reasonable, though, it would be better if the user can configure it according to their specific need. btw, change the update interval is a common feature supported by many top-like monitor tools, for example: nvidia-smi/gpustat/dstat/htop/glances.

**Comment by XuehaiPan** [comment]
I'm afraid we cannot set the snapshot interval longer for device status, because these snapshot results are used for the graph plots.

I can make the interval for process snapshots to be configurable though.

**Comment by uwydoc** [comment]
they are related, but i do not think it is impossible or even hard to make the snapshot interval configurable while keep the graph plot right. ok, maybe i should dig deeper into the code first.
