### ISSUE TITLE
[Question] Which processes are using GPU memory?

### ISSUE THREAD

**Issue by jiapei-nexera** [XuehaiPan/nvitop#19]
What command(s) will be able to tell which process(es) are using GPU memory?

#### Runtime Environment

- Operating system and version: `Ubuntu 22.04 LTS`
- Terminal emulator and version: `gnome-desktop3-data/jammy-updates,jammy-updates,now 42.1-0ubuntu1 all [installed]`
- Python version: `3.10.4`
- NVML version (driver version): `510.73.05`
- `nvitop` version or commit: `nvitop 0.5.6`
- `python-ml-py` version: **??? what is that?**
- Locale: `en_US.UTF-8`

#### Current Behavior

working fine...

#### Expected Behavior

Looking forward to check which processes are using GPU memory ???

#### Context

N/A

#### Possible Solutions

N/A

#### Steps to Reproduce

Just run it... 

```console
nvitop
```

#### Images / Videos  

N/A

**Comment by XuehaiPan** [comment]
> Looking forward to check which processes are using GPU memory?

Hi @jiapei-nexera, I do not quite understand your question. Did you mean how to see the processes on `nvitop`'s GUI? Or looking for a method for Python program integration?

In the terminal GUI, the processes using GPU are listed at the bottom and the column `GPU-MEM` shows the GPU memory consumption:

![Screenshot1](https://user-images.githubusercontent.com/16078332/173758756-014fc410-527b-471f-83c1-8047b9dde0b9.png)

if you press the <kbd>t</kbd> key:

![Screenshot2](https://user-images.githubusercontent.com/16078332/173759016-60d56a4f-30d0-4547-9335-51deded78588.png)

the device that the process running on is shown in the column `DEVICE` (Host for using CPU only).

------

For program integration, please see https://github.com/XuehaiPan/nvitop#process.

The following code retrieves all processes running on the GPU:

```python
from nvitop import Device

all_devices = Device.all()
all_processes = []
for device in all_devices:
    all_processes.extend(device.processes().values())
```

**Comment by jiapei-nexera** [comment]
@XuehaiPan 

Great.... Got you ... Thank you....
