### ISSUE TITLE
Rendering issues caused by locale settings

### ISSUE THREAD

**Issue by ninjaaron87** [XuehaiPan/nvitop#3]
#### Runtime Environment

- Operating system and version: Arch Linux x86_64
- Terminal emulator and version: Alacritty 0.8.0 (a1b13e68)
- Python version: Python 3.9.6
- NVML/CUDA version: nvidia-smi: 465.31 / 11.3
- `nvitop` version/commit: 0.3.5.6
- `python-ml-py` version: 11.450.51
- Locale: USA

#### Current Behavior

1. After following installation instructions running `nvitop` command does not work, `bash` cannot find the command. However, `python -m nvitop` does work. Added `/home/user_name/.local/bin` to enable `nvitop` command to work. 
2. `nvitop` command prints as expected, however, `nvitop -m` colored graphs and formatting for CPU and MEM aren't showing correctly.

side x side comparison      "nvitop -m"(left) vs "nvitop("right)
![image](https://user-images.githubusercontent.com/87574495/126050843-257292e4-85bf-4aa4-8d6a-5a3c0cb14f78.png)

#### Expected Behavior

1. `nvitop` install would set up env var so that command works immediately after install
2. CPU and MEM graphical representation of % used would show and format would match that of `nvitop` command.

#### Possible Solutions

1. `nvitop` install to check/add env var or ReadMe should note for the end-user to check this
2. I'm not sure :( 

#### Steps to reproduce

1. Remove user-added env path, open terminal, and run `nvitop`

2. Run `nvitop -m` or `python3 -m nvitop -m`

**Comment by XuehaiPan** [comment]
Thanks for the feedback!

For the first issue:

> After following installation instructions running "nvitop" command does not work, bash cannot find command.

You shoud add the directory of `nvitop`'s executable in your `PATH`, usually `~/.local/bin` (for installed by `pip3 install ...`) or `/usr/local/bin` (for installed by `sudo pip3 install ...`).

For the second issue:

> `nvitop` command prints as expected, however, `nvitop -m` colored graphs and formatting for CPU and MEM aren't showing correctly.

As the screenshot you have shown, the monitor mode of `nvitop` didn't display the box-drawing characters correctly. As Alacritty does support Unicode characters, does your ncurses library support Unicode (`pacman -Ql ncurses | grep ncursesw`)? `nvitop` will set the `LC_ALL` at startup:

https://github.com/XuehaiPan/nvitop/blob/b669fa39b161e7d482221ccee696d8dd82ed8910/nvitop/cli.py#L58-L64

Possible solutions:

1. set the environment variable `LC_ALL='C.UTF-8'` or `LC_ALL='en_US.UTF-8'` in your shell profile.
2. use `nvitop -m -U` to use ASCII characters only.
