### ISSUE TITLE
Feature request: `--interval SEC` support milli_second

### ISSUE THREAD

**Issue by yantaozhao** [XuehaiPan/nvitop#32]
#### Runtime Environment

- Python version:  `3.9`

#### Current Behavior

cli options:
`--interval SEC`: seconds

#### Expected Behavior

`--interval Milli_SEC`: support milli second, i.e.: not int, but float type

**Comment by XuehaiPan** [comment]
Hi @yantaozhao, thanks for raising this. Could you give a more detailed use case to have non-int intervals?

Too small snapshot interval can cause performance issue (lower than 1 sec). Besides, note that the `--interval` option of `nvitop`'s CLI only affects the interval for process snapshot. The device metric snapshot interval remains 1 sec (not changed by `--interval`).

If you want to use `nvitop` to profile your process performance, maybe you can try [`nvitop.ResourceMetricCollector`](https://github.com/XuehaiPan/nvitop#resource-metric-collector).

**Comment by XuehaiPan** [comment]
Closing due to lack of motivation and use cases. Feel free to ask to reopen this with additional contexts.
