### ISSUE TITLE
Failed to initialize `curses` (setupterm: could not find terminfo database)

### ISSUE THREAD

**Issue by pursuecong** [XuehaiPan/nvitop#38]

**Comment by XuehaiPan** [comment]
@pursuecong Please do not modify the issue template. You should provide some necessary context about your issue, such as your runtime environment and the traceback output.

**Comment by XuehaiPan** [comment]
Closing due to lack of necessary context. Please feel free to ask for a reopening with those contexts added.

I suspect you are using Python inside a conda environment or Jupyter Notebook. Please use a non-conda Python to install `nvitop`, e.g., the system Python:

```bash
/usr/bin/python3 -m pip install --upgrade --user nvitop
```

Then add `~/.local/bin` to your `PATH` in your shell rcfile:

```bash
export PATH="${HOME}/.local/bin:${PATH}"
```

**Comment by pursuecong** [comment]
Thank you

**Comment by KeithTt** [comment]
Same problem here.

`ERROR: Failed to initialize `curses` (curs_set() returned ERR)`

Upgrade nvitop still not work...

**Comment by XuehaiPan** [comment]
> Same problem here.
> 
> `ERROR: Failed to initialize curses (curs_set() returned ERR)`
> 
> Upgrade nvitop still not work...

Hi @KeithTt, did you run nvitop inside a Jupyter notebook or a conda environment? You may try:

```bash
pip3 install --upgrade pipx
pipx run nvitop
```

**Comment by JinaoLiu** [comment]
> > Same problem here.
> > `ERROR: Failed to initialize curses (curs_set() returned ERR)`
> > Upgrade nvitop still not work...
> 
> Hi @KeithTt, did you run nvitop inside a Jupyter notebook or a conda environment? You may try:
> 
> ```shell
> pip3 install --upgrade pipx
> pipx run nvitop
> ```

应该是不能在conda环境里安装， 我是在conda环境中安装报如上错误，但是我将环境切换到base中安装， 是可以的。另外， 感谢作者做了一个这么好用的工具， 非常棒！
