### ISSUE TITLE
error

### ISSUE THREAD

**Issue by reapoker** [XuehaiPan/nvitop#4]
#### Runtime Environment

- Operating system and version: [e.g. Ubuntu 20.04 LTS / Windows 10 Build 19043.1110]
- Terminal emulator and version: [e.g. GNOME Terminal 3.36.2 / Windows Terminal 1.8.1521.0]
- Python version: [e.g. `3.5.6` / `3.9.6`]
- NVML version (driver version): [e.g. `460.84`]
- `nvitop` version or commit: [e.g. `0.3.5.6` / `main@b669fa3`]
- `python-ml-py` version: [e.g. `11.450.51`]
- Locale: [e.g. `C` / `C.UTF-8` / `en_US.UTF-8`]

#### Current Behavior
![image](https://user-images.githubusercontent.com/32959296/128589491-e1960b74-593d-4fcd-aae3-d96804ee1e19.png)

#### Expected Behavior
run as previews

#### Steps to reproduce

1.
2.
3.

#### Traceback

```

```

**Comment by XuehaiPan** [comment]
Did you installed other implementation of NVML Python bindings (`nvidia-ml-py3`, `pynvml`, etc.)? Have a quick check with:

```
pip3 freeze
```

You can fix this with the following command:

```
pip3 install --force-reinstall nvidia-ml-py==11.450.51
```

**Comment by reapoker** [comment]
![image](https://user-images.githubusercontent.com/32959296/128602413-c08e2065-3237-4842-8cbd-6c8630eee75b.png)
![image](https://user-images.githubusercontent.com/32959296/128602426-5c8f168f-f764-4677-b154-523d3877bd39.png)
nvidia-ml-py3, pynvml have installed.
But it still reports the error.
![error](https://user-images.githubusercontent.com/32959296/128589491-e1960b74-593d-4fcd-aae3-d96804ee1e19.png)

**Comment by XuehaiPan** [comment]
> nvidia-ml-py3, pynvml have installed.

`nvidia-ml-py` is conflict with `nvidia-ml-py3` and `pynvml`. All these three packages will install module `pynvml.py`. You should uninstall the others and reinstall `nvidia-ml-py`:

```bash
pip3 uninstall nvidia-ml-py3 pynvml
pip3 install --force-reinstall nvidia-ml-py==11.450.51
```

Or you can create a new virtual environment and install `nvitop` in that.

**Comment by reapoker** [comment]
thx!
![image](https://user-images.githubusercontent.com/32959296/128603328-68586cf1-bb9a-4453-941d-44598fe42bd9.png)
