### ISSUE TITLE
[Feature Request] Show the real memory usage instead of just show the percentage

### ISSUE THREAD

**Issue by fuzihaofzh** [XuehaiPan/nvitop#58]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Motivation

Thanks for this tool. For the memory panel, I can only see the percentage. Is it possible to show the real memory size together?
Thanks

**Comment by XuehaiPan** [comment]
> Is it possible to show the real memory size together?

Hi @fuzihaofzh, have you ever tried the metrics screen? Select a process and press `Enter/Return` key. Also you can press the `t` key to switch to the treeview screen.

**Comment by fuzihaofzh** [comment]
Sorry for not make it clear. I mean this memory for the machine
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/1419566/225385444-06489c8f-7770-48fd-ba1f-1ac06f9f1bb5.png">
I want to see the total memory of current machine (e.g. 35.4G/251G). Maybe make it looks like htop style as follows?
<img width="641" alt="image" src="https://user-images.githubusercontent.com/1419566/225385757-1c6db708-f55a-4e80-915a-b4e69d9f8c31.png">

**Comment by XuehaiPan** [comment]
This is not compatible with the bar charts in `nvitop`. `nvitop` uses box drawing characters, while `htop` is using `|` and colors. It's hard to render texts property when your host memory is almost full. Maybe you can use a terminal multipler like `tmux`.

**Comment by fuzihaofzh** [comment]
Thanks for the comments. I mean, as it can already show the percentage 10.4% in the above figure. It will not be quite hard to add some extra info (35.4G/251G). Or make it a possible option by users? It would be quite cool if I could see the total memory and the memory engaged in my machine. Thanks.
