### ISSUE TITLE
[Question] Custom criteria for `select_devices`

### ISSUE THREAD

**Issue by ioslide** [XuehaiPan/nvitop#60]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Motivation

Can "select_devices" be updated to specify a GPU and policy? If the policy is set to "queue", the specified GPU can be held until it meets the requirements.

**Comment by XuehaiPan** [comment]
> Can "select_devices" be updated to specify a GPU and policy?

You can pass `devices` argument to `select_devices`. Maybe also add `sort=False`.

```python
devices = select_devices(devices, <criteria args>, sort=False)
```

For `nvisel` CLI, use `CUDA_VIRIBLE_DEVICES` and `--no-sort` (`-S`):

```console
$ nvisel -i "GPU-18ef14e9,GPU-849d5a8d" -S [<criteria options>]
5,6
```

------

> If the policy is set to "queue", the specified GPU can be held until it meets the requirements.

You can write your own logic about that. It may be too complex to add in `nvitop.select` natively.

**Comment by XuehaiPan** [comment]
Closing for it is a specific usage and really depends on the hardware setup. Workload management is kind of out of topic. You can always write your own logic for device selection or use specialized software like `slurm`.
