### ISSUE TITLE
[Question] Why fan speed will be set to 0 when nvitop is running

### ISSUE THREAD

**Issue by gglin001** [XuehaiPan/nvitop#61]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [ ] I have tried the latest version of nvitop in a new isolated virtual environment.

### Questions

Hi, big thanks for creating this great tool!

I found that the gpu fans speed will be set to 0 when `nvitop` is running at frontend(even the tempature is ~45C), but I did not found any fan control related code, could you explain how it works? thanks!

**Comment by XuehaiPan** [comment]
> I found that the gpu fans speed will be set to 0 when nvitop is running at frontend(even the tempature is ~45C)

I wonder what's the output of `nvidia-smi`. Did it also report zero?

```console
$ nvidia-smi
Mon Mar 20 12:49:34 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.89.02    Driver Version: 528.49       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:09:00.0  On |                  N/A |
|  0%   44C    P8    41W / 350W |   4456MiB / 24576MiB |      8%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      9996      G   /Xwayland                       N/A      |
|    0   N/A  N/A     17743      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+

$ nvidia-smi --query-gpu=fan.speed --format=csv
fan.speed [%]
0 %
```

> but I did not found any fan control related code, could you explain how it works?

Yes, `nvitop` does not take over your fan control. It only reports status queries from NVML. The NVIDIA driver and operating system control the fan configuration.

**Comment by gglin001** [comment]
<img width="967" alt="Screen Shot 2023-03-20 at 1 14 59 PM" src="https://user-images.githubusercontent.com/13805221/226252616-5bf9936d-6040-4b08-9fdc-3aace5b488f6.png">

```
(pyenv) ➜  ~ nvidia-smi
Mon Mar 20 13:15:42 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090 Ti      Off| 00000000:06:00.0 Off |                    0 |
|  0%   36C    P8               28W / 450W|      0MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
(pyenv) ➜  ~ nvidia-smi --query-gpu=fan.speed --format=csv
fan.speed [%]
0 %

```

the wired thing is that when I quit `nvitop`, the fan will start to run, I did not change the fan settings(coolbit and manual fan control)

**Comment by gglin001** [comment]
from 
https://forums.developer.nvidia.com/t/fan-speed-regression-with-nvidia-beta-470-42-01-and-rtx-3080-fans-dont-stop-on-idle/183604/20
> Please test with driver 520.56.06 which has the fix and share results.
We have updated the nvidia-settings control panel to correctly limit the allowed values for GPUTargetFanSpeed to match the existing valid fan speed ranges for supported NVIDIA GPUs. The valid ranges are 30%-100% for Ampere or newer GPUs, and 1%-100% for older GPUs.

the default fan speed is 30%-100% I think, how can `nvitop` change it 0
I do want to set the fans more silent by the way

**Comment by XuehaiPan** [comment]
> how can `nvitop` change it 0

`nvitop` does not change your configuration. In your screenshot above (https://github.com/XuehaiPan/nvitop/issues/61#issuecomment-1475637638), the output of `nvitop` agrees with `nvidia-smi`, both show the fan percentage are zeros.

It's depending on the hardware, I think. I got fan speed at 22% on idle Ampare GPU.

![Screenshot](https://user-images.githubusercontent.com/16078332/226256971-ce45730f-fe6c-4b19-bfa0-2ac01ef0e94d.png)

**Comment by gglin001** [comment]
I see, Thanks! 

I will do more tests for the weird thing ("when I quit nvitop, the fan will start to run") in the future
