### ISSUE TITLE
[Feature Request] 需要一个GUI版本

### ISSUE THREAD

**Issue by martjay** [XuehaiPan/nvitop#68]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Motivation

<不会代码，安装了使用命令不起作用>

**Comment by XuehaiPan** [comment]
> 安装了使用命令不起作用

你的 `PATH` 环境变量没有设置好。具体怎么设置可以去网上搜索答案。或者你可以使用下面的命令安装：

```bash
python -m pip install nvitop
```

然后使用下面命令执行：

```bash
python -m nvitop
```

这样即使 `PATH` 没有正确设置也能执行。

------

> 需要一个GUI版本

由于缺少运行环境、操作系统等相关信息，我假定你用的是 Windows 操作系统。

`nvitop` 需要 Python 解释器提供运行环境。如果你的意思是提供一个独立的 GUI 程序，则需要内置一个 Python 解释器并一起打包。这违背了 `pip` 包的初衷。

如果说你只是想要一个可以双击打开的 exe 文件，那你使用 `pip` 安装完 `nvitop` 之后，可以在你 Python 安装目录下的 `Scripts` 文件夹找到。

![image](https://user-images.githubusercontent.com/16078332/230759176-3c456eb4-1803-434c-8b84-0f99d73c7bd9.png)
