### ISSUE TITLE
[Feature Request] Add support for prometheus metrics exporter

### ISSUE THREAD

**Issue by sacrex** [XuehaiPan/nvitop#72]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Motivation

能否添加一下metrics exporter这样的server mode，让prometheus和grafana的显示

**Comment by itzikban** [comment]
Will be great ! Thanks

**Comment by XuehaiPan** [comment]
Hi all, I'm quite busy this couple of weeks. I'll investigate this feature by the end of the month.

**Comment by Junyi-99** [comment]
Maybe you can use other metric tools.
