### ISSUE TITLE
[Question]  Installation issue on NVIDIA Jetson AGX Orin (aarch64)

### ISSUE THREAD

**Issue by ramaseshanmcw** [XuehaiPan/nvitop#78]
### Required prerequisites

- [X] I have read the documentation <https://nvitop.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [ ] I have tried the latest version of nvitop in a new isolated virtual environment.

### Questions

So I got this error, when I tried run nvtop.
FATAL ERROR: NVIDIA Management Library (NVML) not found.
HINT: The NVIDIA Management Library ships with the NVIDIA display driver (available at
      https://www.nvidia.com/Download/index.aspx), or can be downloaded as part of the
      NVIDIA CUDA Toolkit (available at https://developer.nvidia.com/cuda-downloads).
      The lists of OS platforms and NVIDIA-GPUs supported by the NVML library can be
      found in the NVML API Reference at https://docs.nvidia.com/deploy/nvml-api.
      
      
     
So I tried to install the display driver which carried the NVML.
   
So, When I tried to install, using bash install-nvidia-driver.sh --package=nvidia-driver-470
I got no package found.
The following packages have unmet dependencies:
 nvidia-driver-530 : Depends: nvidia-driver-535 but it is not installable
E: Unable to correct problems, you have held broken packages. 

Moreover, it seems this particular driver is not suited for AGX Orin. Can you please help me install nvitop on AGX Orin with/without the driver?

![image](https://github.com/XuehaiPan/nvitop/assets/125537024/f4427b62-8861-4b95-80c9-36575dd06ba9)

**Comment by ramaseshanmcw** [comment]
Oh okay. I was using jtop until now. I am actually looking for a better tool. Thank you for your swift response btw.

**Comment by lin-voxvision** [comment]
Hi @XuehaiPan , I like the nvitop more than jtop, so any plans to support jetson?
