### ISSUE TITLE
[Feature Request] Add support for PCIE throughput and NVLink throughput

### ISSUE THREAD

**Issue by lungothrin** [XuehaiPan/nvitop#82]
### Required prerequisites

- [X] I have searched the [Issue Tracker](https://github.com/XuehaiPan/nvitop/issues) that this hasn't already been reported. (comment there if it has.)
- [X] I have tried the latest version of nvitop in a new isolated virtual environment.

### Motivation

It would be nice to be able to monitor throughput between CPU & GPU, and that between different GPUs.

like in Jupyter Lab - GPU dashboards, https://developer.nvidia.com/blog/gpu-dashboards-in-jupyter-lab/

**Comment by XuehaiPan** [comment]
Hi @lungothrin, thanks for raising this. It would be a great feature.

I have added initial results for new query APIs in PR #87.

- #87

Now you can implement your own throughput monitor tools based on that if the PR is merged.

However, for the `nvitop` CLI, there may be no space left to add information for "PCI-e TX/RX" and "NVLink TX/RX". Any thought?
